### DISCUSSION TITLE
Deployment with Docker

### DISCUSSION THREAD

**Discussion by RapidFire05** [masterking32/WoWSimpleRegistration#109] [Ideas]
I like to run all my wow services via docker compose. I ended up creating a dockerfile to build an image for the site. The image ends up being 700ish MB. Probably better ways to do this but it works.

Dockerfile:

```
FROM php:8.3-apache AS registration

COPY ./WoWSimpleRegistration /var/www/html

#Install and update dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libgmp-dev libpng-dev libjpeg-dev libfreetype6-dev libzip-dev libxml2-dev zlib1g-dev libonig-dev sed \
    && curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php \
    && cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gmp gd zip soap mbstring pdo pdo_mysql \
    && php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && apt purge -y --auto-remove \
    && rm -rf /var/lib/apt/lists/* \
    && rm -f /tmp/composer-setup.php

#Enable php modules with sed
RUN sed -i 's/;extension=gd/extension=gd/' $PHP_INI_DIR/php.ini \
    && sed -i 's/;extension=gmp/extension=gmp/' $PHP_INI_DIR/php.ini \
    && sed -i 's/;extension=mbstring/extension=mbstring/' $PHP_INI_DIR/php.ini \
    && sed -i 's/;extension=pdo_mysql/extension=pdo_mysql/' $PHP_INI_DIR/php.ini \
    && sed -i 's/;zend_extension=opcache/zend_extension=opcache/' $PHP_INI_DIR/php.ini \
    && sed -i 's/;opcache.enable=1/opcache.enable=1/' $PHP_INI_DIR/php.ini

WORKDIR /var/www/html/application
RUN composer install
```

Docker Compose:

```
services:
  registration:
      container_name: ac_registration
      hostname: ac_registration
      build:
        context: <path>
        dockerfile: ./master.Dockerfile
        target: registration
      image: ac_registration:latest
      networks:
        - ac_net
      restart: unless-stopped
      tty: true
      stdin_open: true
      volumes: #mount it in so you can change config without rebuilding the image
        - "/path/WoWSimpleRegistration/application/config/config.php:/var/www/html/application/config/config.php"
      ports:
        - "8081:80"
      depends_on:
        mysqldb:
          condition: service_healthy
```
